services:
  - type: web
    name: vidhi-portfolio
    plan: free
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3000
